In [59]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [60]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [61]:
class NeuralNetwork():
    def __init__(self):
        self.optimizer = 'Adam'
        self.loss = 'categorical_crossentropy'
        
    def define(self):
        input_layer= tf.keras.Input(shape=(12, 8, 8))
        x = tf.keras.layers.Conv2D(filters=64,kernel_size = 2,strides = (2,2))(input_layer)
        x = tf.keras.layers.Conv2D(filters=128,kernel_size=2,strides = (2,2))(x)
        x = tf.keras.layers.Conv2D(filters=256,kernel_size=2,strides = (2,2))(x)
        x = tf.keras.layers.Flatten()(x)

        x = tf.keras.layers.Dense(4096,activation = 'relu')(x)
        output = tf.keras.layers.Dense(1,activation = 'sigmoid')(x)

        model = tf.keras.Model(inputs=input_layer,outputs=output)
        model.compile(optimizer = self.optimizer,loss = self.loss)
        self.model = model
nn = NeuralNetwork()
nn.define()

In [62]:
def prepare_output(array):
    return 1/(1 + 10**(array/400))

In [63]:
df = pd.read_csv('data1.csv')
data, evaluations = df.iloc[:,:-1], df.iloc[:,-1:]
# print(data.shape)
# print(data.to_numpy())

# x_train = x_train.reshape(60000, 784).astype("float32") / 255
# x_test = x_test.reshape(10000, 784).astype("float32") / 255

# y_train = y_train.astype("float32")
# y_test = y_test.astype("float32")

# Reserve 10,000 samples for validation
x_val = data[:int(len(data)*0.1)].to_numpy().reshape((-1, 12, 8, 8))
y_val = prepare_output(evaluations[:int(len(data)*0.1)].to_numpy().flatten())
x_train = data[int(len(data)*0.1):int(len(data)*0.9)].to_numpy().reshape((-1, 12, 8, 8))
y_train = prepare_output(evaluations[int(len(data)*0.1):int(len(data)*0.9)].to_numpy().flatten())
x_test = data[int(len(data)*0.9):].to_numpy().reshape((-1, 12, 8, 8))
y_test = prepare_output(evaluations[int(len(data)*0.9):].to_numpy().flatten())
print(x_val[0][3])
print(y_val.shape)
# print(x_train.shape)
# print(x_test.shape)


[[0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
(249,)


In [64]:
history = nn.model.fit(
    x_train,
    y_train,
    batch_size=128,
    epochs=30,
    # We pass some validation for
    # monitoring validation loss and metrics
    # at the end of each epoch
    validation_data=(x_val, y_val),
)

Epoch 1/30
16/16 [==============================] - 1s 26ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 2/30
16/16 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 3/30
16/16 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 4/30
16/16 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 5/30
16/16 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 6/30
16/16 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 7/30
16/16 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 8/30
16/16 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 9/30
16/16 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - val_loss: 0.0000e+00
Epoch 10/30
16/16 [==========================

In [81]:
print("Evaluate on test data")
results = model.evaluate(x_test, y_test, batch_size=128)
print("test loss, test acc:", results)

# Generate predictions (probabilities -- the output of the last layer)
# on new data using `predict`
print("Generate predictions for 3 samples")
predictions = model.predict(x_test[:3])
print("predictions shape:", predictions.shape)

Evaluate on test data
2/2 [==============================] - 0s 4ms/step - loss: 0.6856 - accuracy: 0.9520
test loss, test acc: [0.6856420636177063, 0.9520000219345093]
Generate predictions for 3 samples
1/1 [==============================] - 0s 79ms/step
predictions shape: (3, 2)
